# Generated by Django 3.2.9 on 2021-12-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos_futbol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='year_fundacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
