# Generated by Django 3.2.9 on 2021-12-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos_futbol_app', '0002_alter_equipo_year_fundacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='year_fundacion',
        ),
    ]
