# Generated by Django 3.2.9 on 2021-12-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos_futbol_app', '0003_remove_equipo_year_fundacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='imagen_jugador',
        ),
        migrations.AddField(
            model_name='plantilla',
            name='pais',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
