# Generated by Django 3.2.9 on 2021-12-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos_futbol_app', '0005_auto_20211203_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trofeos',
            name='equipo',
        ),
    ]
