# Generated by Django 3.2.9 on 2021-12-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos_futbol_app', '0006_remove_trofeos_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trofeos',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipos_futbol_app.equipo'),
        ),
    ]
