# Generated by Django 3.2.9 on 2021-12-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos_futbol_app', '0007_trofeos_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trofeos',
            name='copa_europa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trofeos',
            name='copa_liga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trofeos',
            name='copa_rey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trofeos',
            name='copa_uefa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trofeos',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos_futbol_app.equipo'),
        ),
    ]
